sudo: required


services:
    - docker
addons:
  hosts:
    - graph.local.com
    - prom.local.com

language: bash

before_script:
    - docker-compose pull
    - docker-compose up -d
    - docker ps


script:
    - cd config/grafana/
    - ./setupLinux.sh
    - cd ../..
    - pwd
    - echo "yes !"
    - curl prom.local.com/metrics
